#define TILE_WHITE 0
    ____,____,
    ____,____,
    ____,____,
    ____,____,
    ____,____,
    ____,____,
    ____,____,
    ____,____,
#define TILE_BLACK 1
    XXXX,XXXX,
    XXXX,XXXX,
    XXXX,XXXX,
    XXXX,XXXX,
    XXXX,XXXX,
    XXXX,XXXX,
    XXXX,XXXX,
    XXXX,XXXX,
#define TILE_WALL 2
    lX_l,lX_l,
    lXll,lXll,
    lXll,lXll,
    XXXX,XXXX,
    _llX,_llX,
    lllX,lllX,
    lllX,lllX,
    XXXX,XXXX,
#define TILE_BOX_LT 3
    XXXX,XXXX,
    XXXX,XXXX,
    XXXX,XXXX,
    XXXX,XXXX,
    XXXX,XXXX,
    XXXX,XX__,
    XXXX,X__X,
    XXXX,X_XX,
#define TILE_BOX_T 4
    XXXX,XXXX,
    XXXX,XXXX,
    XXXX,XXXX,
    XXXX,XXXX,
    XXXX,XXXX,
    ____,____,
    XXXX,XXXX,
    ____,____,
#define TILE_BOX_RT 5
    XXXX,XXXX,
    XXXX,XXXX,
    XXXX,XXXX,
    XXXX,XXXX,
    XXXX,XXXX,
    __XX,XXXX,
    X__X,XXXX,
    XX_X,XXXX,
#define TILE_BOX_L 6
    XXXX,X_X_,
    XXXX,X_X_,
    XXXX,X_X_,
    XXXX,X_X_,
    XXXX,X_X_,
    XXXX,X_X_,
    XXXX,X_X_,
    XXXX,X_X_,
#define TILE_BOX_R 7
   _X_X,XXXX,
   _X_X,XXXX,
   _X_X,XXXX,
   _X_X,XXXX,
   _X_X,XXXX,
   _X_X,XXXX,
   _X_X,XXXX,
   _X_X,XXXX,
#define TILE_BOX_LB 8
    XXXX,X_XX,
    XXXX,X__X,
    XXXX,XX__,
    XXXX,XXXX,
    XXXX,XXXX,
    XXXX,XXXX,
    XXXX,XXXX,
    XXXX,XXXX,
#define TILE_BOX_B 9
    ____,____,
    XXXX,XXXX,
    ____,____,
    XXXX,XXXX,
    XXXX,XXXX,
    XXXX,XXXX,
    XXXX,XXXX,
    XXXX,XXXX,
#define TILE_BOX_RB 10
    XX_X,XXXX,
    X__X,XXXX,
    __XX,XXXX,
    XXXX,XXXX,
    XXXX,XXXX,
    XXXX,XXXX,
    XXXX,XXXX,
    XXXX,XXXX,
// 11
    0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
// 12
    0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
// 13
    0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
// 14
    0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
// 15
    0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
// 16
    0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
// 17
    0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
#define TILE_J 18
    XXXX,XXXX,
    Xlll,lllX,
    XlXX,XXlX,
    XlX_,_XlX,
    XlX_,_XlX,
    XlXX,XXlX,
    Xlll,lllX,
    XXXX,XXXX,
#define TILE_L 19
    XXXX,XXXX,
    XOOO,OOOX,
    XOOO,OOOX,
    XOOO,OOOX,
    XOOO,OOOX,
    XOOO,OOOX,
    XOOO,OOOX,
    XXXX,XXXX,
#define TILE_O 20
    XXXX,XXXX,
    X___,___X,
    X_XX,XX_X,
    X_XX,XX_X,
    X_XX,XX_X,
    X_XX,XX_X,
    X___,___X,
    XXXX,XXXX,
#define TILE_S 21
    XXXX,XXXX,
    XOOO,OOOX,
    XOXX,XXOX,
    XOX_,_XOX,
    XOX_,_XOX,
    XOXX,XXOX,
    XOOO,OOOX,
    XXXX,XXXX,
#define TILE_T 22
    XXXX,XXXX,
    Xlll,lllX,
    Xl__,__lX,
    Xl_l,lXlX,
    Xl_l,lXlX,
    XlXX,XXlX,
    Xlll,lllX,
    XXXX,XXXX,
#define TILE_Z 23
    XXXX,XXXX,
    Xlll,lllX,
    Xlll,lllX,
    XllX,XllX,
    XllX,XllX,
    Xlll,lllX,
    Xlll,lllX,
    XXXX,XXXX,
#define TILE_I0 24
    XXXX,XXXX,
    Xlll,lOlX,
    XOll,lllX,
    Xlll,lllX,
    XllO,llOX,
    Xlll,lllX,
    XlOl,lllX,
    Xlll,OllX,
#define TILE_I1 25
    XOll,lllX,
    Xlll,lOlX,
    XlOl,lllX,
    Xlll,lOlX,
    XllO,lllX,
    Xlll,llOX,
    XOll,lllX,
    Xlll,lOlX,
#define TILE_I2 26
    Xlll,llOX,
    XOll,lllX,
    XllO,lllX,
    Xlll,OllX,
    Xlll,lllX,
    Xlll,lOlX,
    XOll,lllX,
    Xlll,lOlX,
#define TILE_I3 27
    XOll,lllX,
    Xlll,lllX,
    XlOl,lOlX,
    Xlll,OllX,
    Xlll,llOX,
    XlOl,lllX,
    Xlll,OllX,
    XXXX,XXXX,
#define TILE_H0 28
    XXXX,XXXX,
    Xlll,lOll,
    XOll,llll,
    Xlll,llll,
    XllO,llOl,
    Xlll,llll,
    XlOl,llOl,
    XXXX,XXXX,
#define TILE_H1 29
    XXXX,XXXX,
    llll,lOll,
    llOl,lllO,
    Olll,lOll,
    lllO,llll,
    llll,llOl,
    lOll,llll,
    XXXX,XXXX,
#define TILE_H2 30
    XXXX,XXXX,
    lOll,lOll,
    lllO,llOl,
    llll,Olll,
    lOll,llll,
    llll,lOll,
    lOll,llll,
    XXXX,XXXX,
#define TILE_H3 31
    XXXX,XXXX,
    Olll,lllX,
    llOl,lOlX,
    llll,OllX,
    llll,llOX,
    OlOl,lllX,
    llll,OllX,
    XXXX,XXXX,
